### ISSUE TITLE
service key creation responds with success before the service keys have been successfully created on the atlas cluster

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#4] opened 2020-08-25 14:21 UTC
when using the cf create-service-key command, the credentials are generated and returned instantaneously.

However, it appears to take some time for the user/credential to be created on the MongoDB atlas cluster. Trying to use these credentials immediately after the cf command returns a response results in a failure to connect to the database cluster.

expected behaviour: cf create-service-key command should not return a result until the user/credentials have been successfully created on the Atlas cluster

**Comment by jasonmimick** [comment] 2020-08-26 17:41
This is probably because it takes a period of time for the changes to get rolled out from Atlas to the actual database nodes.

Just like with the old tile, if you called `cf create-service-key` it would take a few moments for Ops Manager to roll out the new db user to each automation agent on the db nodes.

This issue should not be a blocker, since the old tile worked that same way.
 
However, we would like to investigate a technical solution on this item since the overall impact of this timing could be greater now that we're in a fully cloud-based solution. We should build our services to be durable and dependable for users.
Based upon our technical investigation, we will determine the best next step.

**Comment by jasonmimick** [comment] 2020-09-01 18:03
Closing this as working as designed.
Please see comment on [Issue 10](https://github.com/mongodb/atlas-osb/issues/10).
In this case, when the broker calls the Atlas API to create a database user, the API responds with OK and _then_ starts the deployment roll-out to actually push this new user definition to each actual database node in the cluster. This process takes time and therefore causing this particular timing issue.
We would recommend using the same approach as recommended in [Issue 10](https://github.com/mongodb/atlas-osb/issues/10)

**Closed by jasonmimick** 2020-09-01 18:03 UTC
Labels: enhancement
